### ISSUE TITLE
Rename of FactoryGirl to FactoryBot has broken my projects

### ISSUE THREAD

**Issue by iHiD** [thoughtbot/factory_bot_rails#243]
Hello. Sorry for the slightly dramatic issue title, but I couldn't find a gentler way to say it :)

Running bundle update and running tests now gives:
```NameError: uninitialized constant ActionView::TestCase::FactoryGirl```

Renaming `FactoryGirl` to `FactoryBot` everywhere in my code fixes the issue, but I think such a breaking change should result in a Major version increment, not a Patch increment. I would suggest reverting the 4.8 branch to factory_girl and release 5.0 as factory_bot.

**Comment by Euraldius** [comment]
Cross posting from the factory_bot issue https://github.com/thoughtbot/factory_bot/issues/1055#issuecomment-338415458

> Hey! Sorry for the trouble this is causing; we didn't expect it to be a breaking change. The intended behavior is that you see a deprecation warning when you run the test suite. We're investigating now.

**Comment by mjankowski** [comment]
We apologize for the breakage we caused by fumbling the initial gem release.

Here's a blog post with a full explanation and upgrade instructions - https://robots.thoughtbot.com/factory_bot

FG 4.9.0 should be just a deprecation warning now, and getting FB will require a proactive upgrade initiated by developer.
