### ISSUE TITLE
Here is a command to rename all `FactoryGirl`s in your Rails app

### ISSUE THREAD

**Issue by jstumbaugh** [thoughtbot/factory_bot_rails#245]
To view all the files that have the class name `FactoryGirl` in them, you can use
`grep FactoryGirl --recursive --files-with-matches`

However, you may want to exclude some directories from the renaming, mainly the `vendor/` directory.

Running the following command will rename all the `FactoryGirl`s to `FactoryBot` in your app.

`grep FactoryGirl --recursive --files-with-matches --exclude-dir=vendor/ | xargs sed --in-place "s/FactoryGirl/FactoryBot/g"`

**Comment by mjankowski** [comment]
Thanks for this!

We included a similar command in our upgrade instructions - https://github.com/thoughtbot/factory_bot/blob/4-9-0-stable/UPGRADE_FROM_FACTORY_GIRL.md

I'm going to close this issue since there's nothing actionable here. Let me know if you wanted another outcome beyond providing the suggestion.
