### ISSUE TITLE
factory_girl_rails/factory_bot_rails RuntimeError:   can't modify frozen Array

### ISSUE THREAD

**Issue by torntrousers** [thoughtbot/factory_bot_rails#247]
I've followed the instructions in the blog post about how to make the factory_girl_rails/factory_bot_rails rename and now tests fail with 'can't modify frozen Array', eg:
```
RuntimeError:
  can't modify frozen Array
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:2:in `<top (required)>'
# ./spec/models/user_state_machine_spec.rb:1:in `<top (required)>'
```
I'm totally new to rails and Ruby so likely a user error, but what? Any pointers on what I'm doing wrong?

Thanks!

**Comment by joshuaclayton** [comment]
@torntrousers to confirm, pre-rename, you were not seeing this error, correct?

Out of curiosity, is it possible you could provide the git diff from your change? If you're on a Mac, you should be able to run `git show HEAD | pbcopy` and paste in here, or send to me directly, if you've commited the changes.

Another possible culprit: you had a file with the name `factory_girl` in it somewhere in your repo, and when you ran the recommend grep/sed commands, it updated `require "my/factory_girl/file"` to `require "my/factory_bot/file"` without you moving the file.

Without being able to see what changed, it's difficult to nail down what the issue is, but those are the two places I'd start.

**Comment by torntrousers** [comment]
Yes the tests work fine if I change it all back to factory-girl. Here is the git diff:
```
git status
On branch factory-bot-name-change
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Gemfile
	modified:   Gemfile.lock
	modified:   config/application.rb
	modified:   spec/rails_helper.rb

no changes added to commit (use "git add" and/or "git commit -a")
```
and
```
git diff Gemfile
diff --git a/Gemfile b/Gemfile
index c50e9769..b89987dd 100644
--- a/Gemfile
+++ b/Gemfile
@@ -61,7 +61,7 @@ group :test do
   gem "capybara"
   gem "capybara-webkit"
   gem "database_cleaner"
-  gem "factory_girl_rails"
+  gem "factory_bot_rails"
   gem "faker"
   gem "fakeredis", require: "fakeredis/rspec"
   gem "multi_xml"
~/Development/phone-platform> git diff Gemfile.lock
diff --git a/Gemfile.lock b/Gemfile.lock
Rename factory-girl-rails to factory-bot-rails
index 35e081bd..20520657 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -200,10 +200,10 @@ GEM
       activemodel
     erubis (2.7.0)
     execjs (2.7.0)
-    factory_girl (4.8.0)
+    factory_bot (4.8.2)
       activesupport (>= 3.0.0)
-    factory_girl_rails (4.8.0)
-      factory_girl (~> 4.8.0)
+    factory_bot_rails (4.8.2)
+      factory_bot (~> 4.8.2)
       railties (>= 3.0.0)
     faker (1.8.4)
       i18n (~> 0.5)
@@ -517,7 +517,7 @@ DEPENDENCIES
   dotenv-rails (~> 2.1.0)
   dynamic_form
   email_validator
-  factory_girl_rails
+  factory_bot_rails
   faker
   fakeredis
   flag_shih_tzu
```

**Comment by joshuaclayton** [comment]
@torntrousers ah, excellent; can you check to see what changed in `config/application.rb`? Since that showed up in the original backtrace, I wonder if it got changed unexpectedly.

**Comment by torntrousers** [comment]
```
diff --git a/config/application.rb b/config/application.rb
index 4a37cabd..a40b74f6 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -61,7 +61,7 @@ module PhonePlatform

     config.generators do |g|
       g.test_framework      :rspec, :fixture => true
-      g.fixture_replacement :factory_girl, :dir => "spec/factories"
+      g.fixture_replacement :factory_bot, :dir => "spec/factories"
       g.template_engine     :haml
     end
```

**Comment by joshuaclayton** [comment]
@torntrousers ah, apologies - I missed this when you posted the diff.

There's nothing that's immediately obvious to me as actively causing this. Can you provide what command (or commands, if you're able to reproduce in other ways) that trigger this exception? (e.g. were you running `rake`, `rspec spec`, `bundle exec rake`, `rails generate model foo bar baz`)

The fact it travels all the way back to the application, which runs `Bundler.require(*Rails.groups)`, makes me wonder if it's something with spring, maybe, since that's very much in the application load order and is operating on an array that could consider itself modified (since the list of gems has technically changed). Could you run `spring stop` and try whatever command(s) again?

**Comment by torntrousers** [comment]
After doing bundle install to get the error i do "bin/rake parallel:spec". 
I've tried spring stop but it says spring is not running. So I tried restarting the mac but still get "can't modify frozen Array" error. Then switching from my git branch with just this change back to master and doing  bundle install and "bin/rake parallel:spec" and the tests all work fine again.

**Comment by torntrousers** [comment]
Sorted!
The problem was that the grep command given in the blog post to Replace All Constant References didn't actually change all the instances of FactoryGirl in the code base. After we found that and did a global change with Atom it all works fine. 
This is an example diff of one of the files missed by the grep that I had to manually change:
```
git diff spec/factories/activation_code.rb
diff --git a/spec/factories/activation_code.rb b/spec/factories/activation_code.rb
index 493f7942..8c727cb5 100644
--- a/spec/factories/activation_code.rb
+++ b/spec/factories/activation_code.rb
@@ -1,4 +1,4 @@
-FactoryGirl.define do
+FactoryBot.define do
   factory :activation_code do
     code { Faker::Lorem.characters(6) }
     code_valid { true }
```
Something like this grep looks like  it fixes it:
```grep -rl 'FactoryGirl' ./ | xargs sed -i '' 's/FactoryGirl/FactoryBot/g'```

**Comment by joshuaclayton** [comment]
@torntrousers ah, excellent! I hadn't thought to ask about if other constants existed; I'd actually just attempted to recreate by adding parallel_tests to a repo 😃 to see if that was involved.

I'm glad to hear it! We ended up updating the command suggested in [the upgrade doc](https://github.com/thoughtbot/factory_bot/blob/4-9-0-stable/UPGRADE_FROM_FACTORY_GIRL.md#replace-all-constant-references) since some people won't have rakefiles that include it (so, we added the `-s` flag for silencing unmatched files instead of failing).

I'm glad to hear it worked out, and thanks for your patience while we debugged; without access to the codebase, these problems are always a bit trickier!

**Comment by joshuaclayton** [comment]
@JalisoCSP did any other gems get bumped in the upgrade? Can you provide a backtrace, and perhaps the line(s) that seem to be causing the problem?

**Comment by JalisoCSP** [comment]
Fast response! There was a few, but we've since narrowed it down to this gem being bumped - eg; we took this upgrade out and everything was fine.

```
Failure/Error: require File.expand_path("../../config/environment", __FILE__)

FrozenError:
  can't modify frozen Array

# ./config/environment.rb:17:in `<top (required)>'
# ./spec/spec_helper.rb:14:in `<top (required)>'
# ./spec/<our_spec_file>_spec.rb:1:in `<top (required)>'

respectively:
-> Rails.application.initialize!
-> require File.expand_path("../../config/environment", __FILE__)
-> require 'spec_helper'
```

**Comment by joshuaclayton** [comment]
@JalisoCSP is there further backtrace you can provide? There's nothing obvious/unique here that would point to FB - or really anything else - directly, so it's hard to provide any suggestions right now.

**Comment by JalisoCSP** [comment]
@joshuaclayton nothing too useful, I'm afraid.

Here it is, in case it helps:

```
An error occurred while loading .<spec_path>_spec.rb.
Failure/Error: require File.expand_path("../../config/environment", __FILE__)

FrozenError:
  can't modify frozen Array
# [...]/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:76:in `insert'
# [...]/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:76:in `insert'
# [...]/.rvm/gems/ruby-2.5.1/gems/sentry-raven-2.7.4/lib/raven/integrations/rails.rb:10:in `block in <class:Rails>'
# [...]/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
# [...]/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
# [...]/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
# [...]/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
# [...]/.rvm/gems/ruby-2.5.1/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
# ./config/environment.rb:17:in `<top (required)>'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# ./spec/spec_helper.rb:14:in `<top (required)>'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# .<spec_path>_spec.rb:1:in `<top (required)>'
# [...]/.rvm/gems/ruby-2.5.1/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:82:in `load'
# [...]/.rvm/gems/ruby-2.5.1/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:82:in `load'
# [...]/.rvm/gems/ruby-2.5.1/gems/zeus-0.15.14/lib/zeus/load_tracking.rb:74:in `load'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# [...]/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
```
This is on Rails 5.2.1 and Ruby 2.5.1

**Comment by KelseyDH** [comment]
Having the same problem after changing to FactoryBot from FactoryGirl and `factory_girl_rails` to `factory_bot_rails`

**Comment by kirylpl** [comment]
In my case issue was caused by rails_admin recent upgrade:

```
RuntimeError:
  Required middlewares for RailsAdmin are not added
  To fix tihs, add

    config.middleware.use ActionDispatch::Flash

  to config/application.rb.
```

**Comment by joethrive** [comment]
Just upgraded from rails 4.2 to 5.2 (ruby 2.3.1) and started getting this message.  Switched from FactoryGirl to FactoryBot and the problem continues.  If you want to keep this issue closed I can open a new one, but figured this was the best place.


<pre>
An error occurred while loading ./spec/models/user_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

RuntimeError:
  can't modify frozen Array
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/models/user_spec.rb:26:in `<top (required)>'
Run options: include {:focus=>true}
</pre>

**Comment by joethrive** [comment]
Happy to get you as much detail as you need, not 100% sure the problem is on FB.

Here's the full stack trace from rspec:
<pre>
An error occurred while loading ./spec/models/user_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

RuntimeError:
  can't modify frozen Array
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/engine.rb:581:in `unshift'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/engine.rb:581:in `block in <class:Engine>'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `each'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
# ./config/environment.rb:5:in `<top (required)>'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
# ./spec/models/user_spec.rb:26:in `<top (required)>'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in `load_file_handling_errors'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1560:in `block in load_spec_files'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in `each'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in `load_spec_files'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:98:in `setup'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:86:in `run'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/joe/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.8.0/exe/rspec:4:in `<top (required)>'
# /Users/joe/.rbenv/versions/2.3.1/bin/rspec:23:in `load'
# /Users/joe/.rbenv/versions/2.3.1/bin/rspec:23:in `<main>'
Run options: include {:focus=>true}</pre>

**Comment by Mohakjuneja** [comment]
> @joshuaclayton nothing too useful, I'm afraid.
> 
> Here it is, in case it helps:
> 
> ```
> An error occurred while loading .<spec_path>_spec.rb.
> Failure/Error: require File.expand_path("../../config/environment", __FILE__)
> 
> FrozenError:
>   can't modify frozen Array
> # [gem path]/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:76:in `insert'
> # [gem path]/actionpack-5.2.1/lib/action_dispatch/middleware/stack.rb:76:in `insert'
> # [gem path]/sentry-raven-2.7.4/lib/raven/integrations/rails.rb:10:in `block in <class:Rails>'
> # [gem path]/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
> # [gem path]/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
> # [gem path]/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
> # [gem path]/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
> # [gem path]/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
> # ./config/environment.rb:17:in `<top (required)>'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
> # ./spec/spec_helper.rb:14:in `<top (required)>'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
> # .<spec_path>_spec.rb:1:in `<top (required)>'
> # [gem path]/zeus-0.15.14/lib/zeus/load_tracking.rb:82:in `load'
> # [gem path]/zeus-0.15.14/lib/zeus/load_tracking.rb:82:in `load'
> # [gem path]/zeus-0.15.14/lib/zeus/load_tracking.rb:74:in `load'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `block in load'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
> # [gem path]/activesupport-5.2.1/lib/active_support/dependencies.rb:281:in `load'
> ```
> This is on Rails 5.2.1 and Ruby 2.5.1
> 
> (Edits: Bad copy and paste when removing long [gem path] 👍)

How did you resolve this? I've been struggling with the same error

**Comment by JalisoCSP** [comment]
> How did you resolve this? I've been struggling with the same error

We never did. We're still on 4.10.0

CC: @Mohakjuneja

**Comment by composerinteralia** [comment]
The stack trace given on rails/rails#33745 looks fairly similar to this, and it seems to have been related to a [rails_admin initializer]( https://github.com/sferik/rails_admin/commit/94928d1de7cf6fd01ee19ed7a94f17c91e19282d) running after the `build_middleware_stack` initializer.

The `build_middleware_stack` initializer freezes the middleware array:

* https://github.com/rails/rails/blob/cfc48d0b5f363cc880237d2e25598c64c9eb8400/railties/lib/rails/application/finisher.rb#L46
* https://github.com/rails/rails/blob/3cac5fe94f0f81b4263cfa03d4822c05a55eb49c/railties/lib/rails/application.rb#L515
* https://github.com/rails/rails/blob/3cac5fe94f0f81b4263cfa03d4822c05a55eb49c/railties/lib/rails/engine.rb#L505
* https://github.com/rails/rails/blob/fc5dd0b85189811062c85520fd70de8389b55aeb/actionpack/lib/action_dispatch/middleware/stack.rb#L100

From the stack trace in this issue, it looks like when [sentry-raven inserts its middleware](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rails.rb#L10) it is happening after the middleware array has been frozen.

I don't see how factory_bot_rails could have much effect here, since we don't do anything with middleware at all, but we did just got a new issue about this: #303.

**Comment by lstone** [comment]
This happened to me when I declared two factories w/ the same name.

**Comment by composerinteralia** [comment]
See https://github.com/thoughtbot/factory_bot_rails/issues/303#issuecomment-434560625 for more details

**Comment by nezirz** [comment]
I had the same problem when tried to upgrade from rails 5.2.0 to 5.2.2.1 using bundle update rails command, its also updated many other gems one of them was factory_bot from 4.10.0 to 5.0.2 so solution was to downgrade to 4.10.0 by specifying the version number for factory_bot to   gem "factory_bot_rails", "~> 4.10.0"

**Comment by composerinteralia** [comment]
@nezirz there were some deprecations in factory_bot 4.11, so you will want to upgrade to that version and deal with the warnings before upgrading to factory_bot 5.0.

**Comment by AlessandroMinali** [comment]
Great tip @composerinteralia.

basically to solve this issue:
```
rubocop \
  --require rubocop-rspec \
  --only FactoryBot/AttributeDefinedStatically \
  --auto-correct
```

The errors with 5.0 occur because of the deprecation of static var in factories. Gl all.

**Comment by pavkosykh** [comment]
> Great tip @composerinteralia.
> 
> basically to solve this issue:
> 
> ```
> rubocop \
>   --require rubocop-rspec \
>   --only FactoryBot/AttributeDefinedStatically \
>   --auto-correct
> ```
> The errors with 5.0 occur because of the deprecation of static var in factories. Gl all.

Thanks a lot, this helped to solve problem!

**Comment by schmijos** [comment]
The update 5.0.1 → 5.0.2 makes this occur again?
![image](https://user-images.githubusercontent.com/245443/56885330-7f85d400-6a6c-11e9-8490-77736c5feb28.png)

**Comment by composerinteralia** [comment]
@schmijos there are no intentional breaking changes from factory_bot_rails 5.0.1 to 5.0.2. The FrozenError is not coming from factory_bot (see https://github.com/thoughtbot/factory_bot_rails/issues/303 for details). If you want to see the underlying factory_bot error try running just one of the failing specs at a time.

**Comment by deepak-sweeten** [comment]
I was getting the same error. I fixed by removing require 'rails_helper' from spec files. It was causing the issue for me. I am not sure but it seems somewhere it was trying to load these helpers multiple time and it was causing can't modify frozen Array.

**Comment by Jellyfishboy** [comment]
I am currently getting the error `undefined method 'dta_find_by' for #<Class:0x00007f848cef2ff0>` when running a single spec at a time. Randomly started doing this...

**Comment by marcelobarreto** [comment]
In my case, just change my factory field from `password 123456` to `password { 123456}` solved.

**Comment by mike927** [comment]
`gem install rubocop-rspec`
and then
`rubocop --require rubocop-rspec --only FactoryBot/AttributeDefinedStatically --auto-correct
`

worked for me

**Comment by slavaZim** [comment]
This can happen if you redefine built-in scope for a model which has a factory.

In my case I defined a scope `except`, which is already defined by `ActiveRecord`.  Changing scope name solved this issue for me.
