### ISSUE TITLE
v4.9.0 is a release tag but doesn't exist in ruby gems?

### ISSUE THREAD

**Issue by kilgore5** [thoughtbot/factory_bot_rails#255]
<img width="1045" alt="screen shot 2018-01-04 at 2 38 28 pm" src="https://user-images.githubusercontent.com/608048/34581065-1e15f38c-f15d-11e7-881c-d75e0671a4b9.png">
<img width="1154" alt="screen shot 2018-01-04 at 2 37 57 pm" src="https://user-images.githubusercontent.com/608048/34581068-2014dd06-f15d-11e7-96b6-5c54f2e3ba6c.png">

**Comment by jeremywadsack** [comment]
It appears that `factory_girl_rails` _does_ exist with 4.9 release, and depends on 4.9 release of `factory_girl` which also isn't a `factory_bot` release.

Looking at the [difference](https://github.com/thoughtbot/factory_bot/compare/v4.8.2...v4.9.0) the 4.9.0 release of `factory_girl` adds the deprecation notice to upgrade to `factory_bot`.

This was confusing because I tried to "upgrade" but had to _downgrade_ the version number.

**Comment by corsonknowles** [comment]
Seriously, it's not like 100s of 1000s of repos use this gem and are upgrading...

**Comment by mjankowski** [comment]
The `4.9.0` github release tag was for the last (probably final) release of `factory_girl_rails`. You can verify this by browsing the code in the tagged release - https://github.com/thoughtbot/factory_bot_rails/tree/v4.9.0

Because we renamed the repository, that tag is still around in what appears now to be the `factory_bot_rails repo`, which I suspect is what is leading to the confusion here.

I'm going to close this issue because the very narrow issue of "why does this tag exist when there is not a rubygems release?" is intentional and not a forgotten release or something ... but we're going to think about what else we might be able to do here to improve clarity around upgrade and reduce confusion around version numbers. Worst case, this will all resolve itself whenever there is another release that requires a version bump, because it will likely be higher than both the latest `_bot_` release and also the final `_girl_` release.

**Comment by kilgore5** [comment]
@mjankowski the simplest step seems to be a note on the tag release v4.9.0: "do not use if using factory_bot_rails"

Particularly since it seems it may be a while until the next release... https://github.com/thoughtbot/factory_bot_rails/compare/v4.9.0...master
