### ISSUE TITLE
Just tell us how to use it

### ISSUE THREAD

**Issue by cpapidas** [thoughtbot/factory_bot_rails#274]
How can we integrate with rails?

Could provide the step by step installation guide?

Any example, how can I use it?

Where is the documentation?

**Comment by composerinteralia** [comment]
https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md

**Comment by cpapidas** [comment]
https://github.com/thoughtbot/factory_bot_rails/pull/275

**Comment by composerinteralia** [comment]
I see you closed #275. Since the `factory_bot_rails` README already has a few links to `factory_bot`, and it does indicate that this is the Rails integration for `factory_bot`, I am going to close this issue. I think there is still room for some documentation improvements on `factory_bot`, but I will track that separately over there. Thanks for your help.
