### ISSUE TITLE
Gradually fix RuboCop todos

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/factory_bot_rails#293]
We added a .rubocop.yml in https://github.com/thoughtbot/factory_bot_rails/commit/29249b375168e06d9d8f23ea365f511cb63a00c6 with a bunch of todos. It would be nice to gradually fix them. I would like to do it one at a time so nobody has to review a giant PR. 😸

**Comment by petestreet** [comment]
Hi @composerinteralia! I made a few PRs, grouped according to specific files or directories that were flagged by rubocop: https://github.com/thoughtbot/factory_bot_rails/pull/295, https://github.com/thoughtbot/factory_bot_rails/pull/296, https://github.com/thoughtbot/factory_bot_rails/pull/297, https://github.com/thoughtbot/factory_bot_rails/pull/298, and https://github.com/thoughtbot/factory_bot_rails/pull/299

A few notes: 
I wanted to get feedback before addressing `Layout/IndentHeredoc`. Rubocop suggests adding an additional dependencies such as ActiveSupport [link] for sub-2.3 Ruby versions, and using the `<<~` syntax otherwise, and I wasn’t sure which approach made more sense in the context of this gem. 

I also haven’t addressed `Metrics/LineLength` at all yet, but would be happy to do that after the other PRs are in. 

There are also a few PR-specific caveats that I made mention of for https://github.com/thoughtbot/factory_bot_rails/pull/296 and https://github.com/thoughtbot/factory_bot_rails/pull/299. 

After the PRs are in, I can go back and clear our the empty cops from `.rubocop.yml` 

Thanks!
