### ISSUE TITLE
Undefined method 'password' in 'admin' factory

### ISSUE THREAD

**Issue by Naveen7696** [thoughtbot/factory_bot_rails#313]
Hello,
I tried factory_bot_rails latest version  on a project with Rails 5.0.7 app 
Getting this error:
..
NoMethodError: undefined method 'password' in 'admin' factory
       /app/vendor/bundle/ruby/2.4.0/gems/factory_bot-5.0.0/lib/factory_bot/definition_proxy.rb:97:in `method_missing'
       /app/spec/factories/admins.rb:4:in `block (2 levels) in <top (required)>'
       /app/vendor/bundle/ruby/2.4.0/gems/factory_bot-5.0.0/lib/factory_bot/syntax/default.rb:18:in `instance_eval'
       /app/vendor/bundle/ruby/2.4.0/gems/factory_bot-5.0.0/lib/factory_bot/syntax/default.rb:18:in `factory'
..

after switching back to 4.8.2 the problem goes away...

**Comment by composerinteralia** [comment]
I am guessing it is a result of static attributes being deprecated. Can you try upgrading to 4.11.1 first to see if you get any deprecation warnings?

**Comment by gnclmorais** [comment]
Ah, the Rubocop is for rspec, not minitest… 😭

**Comment by composerinteralia** [comment]
@gnclmorais It is officially only for RSpec, but others have made it work with minitest: https://github.com/thoughtbot/factory_bot/issues/1173#issuecomment-421410343

**Comment by gnclmorais** [comment]
Wow, I was not expecting getting an answer — specially such a useful one! Thank you, @composerinteralia! 🙇🏻‍♂️

**Comment by KurtRMueller** [comment]
I think a more informative error message would be helpful in this instance.

**Comment by composerinteralia** [comment]
I merged https://github.com/thoughtbot/factory_bot/pull/1287 to add a “Did you mean?” style suggestion to the error. I will try to get that released next week.

**Comment by KurtRMueller** [comment]
Thank you for the work you do!

**Comment by promisepreston** [comment]
I think a more explicit answer would have greatly helped.

From the blog by Thoughbot, I came to realize that statically defined attributes have been deprecated from  factory_bot >= 5.0. And so rather than use statically defined attributes for your factories, use dynamically defined attributes

Here's an example

**Use Dynamically defined attribues**
`factory :robot do`
  `name { "Ralph" }`
  `email { "ralph@example.com" }`
`end`

**And not statically defined attributes**

`factory :robot do`
  `name "Ralph"`
`email  "ralph@example.com"`
`end`

You can read up more about it here
[https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11](url)

**Comment by ryanzidago** [comment]
@promisepreston thank you for your answer. This worked for me.

**Comment by composerinteralia** [comment]
Since this change has been out now for over a year, and since we release an improvement to the error message that this issue was originally opened for, I am going to close this issue now. Thanks everyone for your contributions here!
